version: '3'

services:
  # Angular App
  fe-angular:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run fe-angular:dev:docker
    ports:
      - 4200:4200

  # Express App
  be-express:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run be-express:dev:docker
    ports:
      - 3333:3333

volumes:
  mono-node-modules: null